export default {
	USER_STORE: '@session/USER_STORE',
	ASYNC_USER_STORE: '@session/ASYNC_USER_STORE',
	USER_STORE_ERROR: '@session/USER_STORE_ERROR',

	USER_LOGIN: '@session/USER_LOGIN',
	ASYNC_USER_LOGIN: '@session/ASYNC_USER_LOGIN',
	USER_LOGIN_ERROR: '@session/USER_LOGIN_ERROR',

	LOAD_SESSION: '@session/LOAD_SESSION',
	ASYNC_LOAD_SESSION: '@session/ASYNC_LOAD_SESSION',
	LOAD_SESSION_ERROR: '@session/LOAD_SESSION_ERROR',
}
