export default {
	GET_PROFILE: '@profile/GET_PROFILE',
	ASYNC_GET_PROFILE: '@profile/ASYNC_GET_PROFILE',
	GET_PROFILE_ERROR: '@profile/GET_PROFILE_ERROR',

	STORE_PROFILE: '@profile/STORE_PROFILE',
	ASYNC_STORE_PROFILE: '@profile/ASYNC_STORE_PROFILE',
	STORE_PROFILE_ERROR: '@profile/STORE_PROFILE_ERROR',

	STORE_EXPERIENCE: '@profile/STORE_EXPERIENCE',
	ASYNC_STORE_EXPERIENCE: '@profile/ASYNC_STORE_EXPERIENCE',
	STORE_EXPERIENCE_ERROR: '@profile/STORE_EXPERIENCE_ERROR',

	STORE_EDUCATION: '@profile/STORE_EDUCATION',
	ASYNC_STORE_EDUCATION: '@profile/ASYNC_STORE_EDUCATION',
	STORE_EDUCATION_ERROR: '@profile/STORE_EDUCATION_ERROR',

	DESTROY_EXPERIENCE: '@profile/DESTROY_EXPERIENCE',
	ASYNC_DESTROY_EXPERIENCE: '@profile/ASYNC_DESTROY_EXPERIENCE',
	DESTROY_EXPERIENCE_ERROR: '@profile/STORE_EXPERIENCE_ERROR',

	DESTROY_EDUCATION: '@profile/DESTROY_EDUCATION',
	ASYNC_DESTROY_EDUCATION: '@profile/ASYNC_DESTROY_EDUCATION',
	DESTROY_EDUCATION_ERROR: '@profile/STORE_EDUCATION_ERROR',

	DESTROY_ACCOUNT: '@profile/DESTROY_ACCOUNT',
	ASYNC_DESTROY_ACCOUNT: '@profile/ASYNC_DESTROY_ACCOUNT',
	DESTROY_ACCOUNT_ERROR: '@profile/STORE_ACCOUNT_ERROR',

	GET_PROFILES: '@profile/GET_PROFILES',
	ASYNC_GET_PROFILES: '@profile/ASYNC_GET_PROFILES',
	GET_PROFILES_ERROR: '@profile/GET_PROFILES_ERROR',

	ASYNC_GET_PROFILE_BY_ID: '@profile/ASYNC_GET_PROFILE_BY_ID',

	GET_REPOS: '@profile/GET_REPOS',
	ASYNC_GET_REPOS: '@profile/ASYNC_GET_REPOS',
	GET_REPOS_ERROR: '@profile/GET_REPOS_ERROR',

	CLEAR_PROFILE: '@profile/CLEAR_PROFILE',
	SET_LOADING: '@profile/SET_LOADING',
}
