export default {
	GET_PROFILE: '@profile/GET_PROFILE',
	ASYNC_GET_PROFILE: '@profile/ASYNC_GET_PROFILE',
	GET_PROFILE_ERROR: '@profile/GET_PROFILE_ERROR',

	STORE_PROFILE: '@profile/STORE_PROFILE',
	ASYNC_STORE_PROFILE: '@profile/ASYNC_STORE_PROFILE',
	STORE_PROFILE_ERROR: '@profile/STORE_PROFILE_ERROR',

	CLEAR_PROFILE: '@profile/CLEAR_PROFILE',
	SET_LOADING: '@profile/SET_LOADING',
}
