version: "3"

services:
  database:
    image: mongo
    container_name: dev_connector_mongo
    hostname: mongodb
    env_file:
      - .env
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - ./.docker/dev_connector_mongo:/data/db
