version: "3"

services:
  database:
    image: mongo
    container_name: dev_connector_mongo
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE=test: ${MONGO_NAME}
    ports:
      - 27017:27017
